import type { Metadata, Viewport } from "next";
import { JetBrains_Mono, Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: "400"
})

const brains = JetBrains_Mono({
  variable: "--font-brains",
  weight: "variable"
})

export const metadata: Metadata = {
  title: "Math Exercises To Handle",
  description: "Generated by create next app",
}

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  interactiveWidget: 'resizes-content',
}

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${brains.variable} h-full font-brains antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background text-white">
        { children }
      </body>
    </html>
  )
}
