import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: "400"
})

export const metadata: Metadata = {
  title: "Math Exercises To Handle",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-neutral-900 text-white">
        { children }
      </body>
    </html>
  )
}
